### ISSUE TITLE
Provide option to set shortcuts in plugin settings

### ISSUE THREAD

**Issue by lukasoppermann** [tomcardoso/atom-html-entitize#1]
Hey,

it would be neat if you could add some default shortcuts and allow the user to change those in the plugin settings.

**Comment by tomcardoso** [comment]
I dunno, I think it's probably best to just let users manually set shortcuts. Would really suck to have keymappings overwritten without your knowledge.

**Comment by lukasoppermann** [comment]
Well, for users it is a lot easier to set a shortcut if the option is available in the plugins settings. If possible maybe you could just add the settings to the packages setting page but leave it empty? That would be fine from my point of view.

Thanks for the very handy package in any case.
